

POST http://localhost:9091/auth/login
Content-Type: application/json

{
    "username": "root",
    "password": "2019"
}

###


POST http://localhost:9091/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoicm9vdCIsImZ1bGxOYW1lIjoiVE9ETy4uLiJ9.rJIQW81EeQTsYBBZbEuUKmu_oLsbn02W-ebDJJ-SoDXJU6H0qKQ58G_jWwS0vnnAbwZ9w59gVb3fmwb1ZbcNN9SRNXHw_oS3IcQ-Vm8oBeX-AZ6BGGWr-0iEROWrlIYgSLrlPh6BRUZCTEIWgGISSwxRQQzi4cDnRT7qIvZixtM"
}

###

DELETE http://localhost:9091/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTI2MTUwOTgsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJyb290IiwiZnVsbE5hbWUiOiJUT0RPLi4uIn0.SHzn-To9b_7m1j2QFlNhXpwscqU8EqixDZN0ciZDTh-HvfJr3PS0R0r2FHMxkMbSJs_sUl62NoOX21BUm0VSeelWVdasUqlydx02iWaw8wWKvzlCN2ZazAs_0T93Yaie11JQQPV7ML-eIoJ3vA-tqnJ09stwOehlmg1OPObdvkQ

###


PUT http://localhost:9091/auth/change-pw
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTIyMzAxODgsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJyb290IiwiZnVsbE5hbWUiOiJUT0RPLi4uIn0.Y_MBIfkwRw-h4jhuEfq9wD3HXT7_PDkRz8WgZuElmTZXQbxxZ0mHVakqjeqAJX5J0jFCGuf3_5c6YB_vvNTDdfB7NUBKWQarTz0XZ9_Vwo6SK0ZecgeRSBxtHeN4R0IAoraVgIqmdwv2TVrCXLYFnRDrJDb9T91sZdi-eiyyxG4

{
    "currentPassword": "2019",
    "newPassword": "2019"
}