name: skyone_mobile
description: Skyone System

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  provider: ^4.3.2
  rxdart: ^0.24.1
  flutter_bloc: ^6.0.1
  bloc: ^6.0.1
  json_annotation: ^3.1.0
  json_serializable: ^3.5.0
  get: ^3.26.0
  tuple: ^1.0.3
  shared_preferences: ^0.5.10
  flutter_html: ^1.0.2
  intl_translation: ^0.17.10+1
  devicelocale: ^0.3.1
  bot_toast: ^3.0.4
  firebase_messaging: ^7.0.0
  get_it: ^4.0.4
  font_awesome_flutter: ^8.8.1
  flutter_svg: ^0.19.0
  google_sign_in: ^4.5.3
  # sign_in_with_apple: ^2.5.2
  flutter_facebook_login: ^3.0.0
  # flutter_zalo_login: ^0.1.4
  numberpicker: ^1.2.1
  international_phone_input: ^1.0.4
  flutter_libphonenumber: ^0.3.8
  email_validator: ^1.0.5
  intl: ^0.16.1
  grpc: ^2.9.0
  protobuf: ^1.1.1
  remove_accentuation_extension: ^0.0.2
  flutter_treeview: ^0.7.1+1
  speech_to_text: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.3
  lint: ^1.2.0


dependency_overrides:
  flutter_svg: ^0.18.0
  analyzer: ^0.40.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/notification.svg
    - assets/event.svg
    - assets/calendar.svg
    - assets/task.svg
    - assets/filter.svg
    - assets/message.svg
    - assets/menu.svg
    - assets/search.svg
    - assets/setting.svg
    - assets/user.svg
    - assets/inventory.svg
    - assets/zalo.svg
    - assets/zalo.jpeg
    - assets/logo.png
    - assets/test.jpg
