FROM nginx
COPY ./skyhub-ssl.conf /etc/nginx/conf.d/skyhub-ssl.conf
COPY ./skyhub.conf /etc/nginx/conf.d/skyhub.conf
COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY ./skyhub.crt /etc/nginx/
COPY ./skyhub.key /etc/nginx/
