GET http://localhost:9091/branch?fromOrgType=1&toOrgType=10&includeDisabled=true&includeDeleted=true
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTg5MDE4NTUsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJyb290IiwiZnVsbE5hbWUiOiJUT0RPLi4uIn0.ewgDwncfyBlZrHafBoJWFr0zvErkcVFmmtGwwDidQO_cK2BA-y5BRLABuGa6BUZn17ZUs4qHJT4hq9GMfXqmt144dT9lZud3h5gR5EM96pv013eeMxDVAugapGfkTuvrY8tMINdmeakZmvduHipTXNk5JFMx9EmMPFnepwqo4qU


###
GET http://localhost:9091/department?branchId=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTg5MDE4NTUsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJyb290IiwiZnVsbE5hbWUiOiJUT0RPLi4uIn0.ewgDwncfyBlZrHafBoJWFr0zvErkcVFmmtGwwDidQO_cK2BA-y5BRLABuGa6BUZn17ZUs4qHJT4hq9GMfXqmt144dT9lZud3h5gR5EM96pv013eeMxDVAugapGfkTuvrY8tMINdmeakZmvduHipTXNk5JFMx9EmMPFnepwqo4qU


###

GET http://localhost:9091/department/last?branchId=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTg5MDE4NTUsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJyb290IiwiZnVsbE5hbWUiOiJUT0RPLi4uIn0.ewgDwncfyBlZrHafBoJWFr0zvErkcVFmmtGwwDidQO_cK2BA-y5BRLABuGa6BUZn17ZUs4qHJT4hq9GMfXqmt144dT9lZud3h5gR5EM96pv013eeMxDVAugapGfkTuvrY8tMINdmeakZmvduHipTXNk5JFMx9EmMPFnepwqo4qU

###

GET http://localhost:9091/org/role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTg5MDE4NTUsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJyb290IiwiZnVsbE5hbWUiOiJUT0RPLi4uIn0.ewgDwncfyBlZrHafBoJWFr0zvErkcVFmmtGwwDidQO_cK2BA-y5BRLABuGa6BUZn17ZUs4qHJT4hq9GMfXqmt144dT9lZud3h5gR5EM96pv013eeMxDVAugapGfkTuvrY8tMINdmeakZmvduHipTXNk5JFMx9EmMPFnepwqo4qU


###

GET http://localhost:9091/org?parentId=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTg5MDE4NTUsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJyb290IiwiZnVsbE5hbWUiOiJUT0RPLi4uIn0.ewgDwncfyBlZrHafBoJWFr0zvErkcVFmmtGwwDidQO_cK2BA-y5BRLABuGa6BUZn17ZUs4qHJT4hq9GMfXqmt144dT9lZud3h5gR5EM96pv013eeMxDVAugapGfkTuvrY8tMINdmeakZmvduHipTXNk5JFMx9EmMPFnepwqo4qU


###

GET http://localhost:9091/org/menu?orgIds=1,2,3,4,5,6,7,8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTg5MDE4NTUsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJyb290IiwiZnVsbE5hbWUiOiJUT0RPLi4uIn0.ewgDwncfyBlZrHafBoJWFr0zvErkcVFmmtGwwDidQO_cK2BA-y5BRLABuGa6BUZn17ZUs4qHJT4hq9GMfXqmt144dT9lZud3h5gR5EM96pv013eeMxDVAugapGfkTuvrY8tMINdmeakZmvduHipTXNk5JFMx9EmMPFnepwqo4qU
